Repository netboxlabs/netbox-learning, pull requests merged in 2024-12, with the labels that each got.

#23 More Automation Zero to Hero updates
  automation-zero-to-hero/README.md
  automation-zero-to-hero/docs/3_Source_Of_Truth_NetBox.md
  automation-zero-to-hero/docs/5_Monitoring_Icinga.md
  automation-zero-to-hero/docs/7_Automated_Network_Changes_Ansible.md
  automation-zero-to-hero/docs/Installation.md
  automation-zero-to-hero/docs/images/videos/AutomatedNetworkChanges.png
  automation-zero-to-hero/docs/images/videos/MonitoringIcinga.png
Labels: documentation, Markdown

#24 Added Summary video
  automation-zero-to-hero/docs/8_Summary.md
  automation-zero-to-hero/docs/images/videos/Summary.png
Labels: documentation, Markdown

#25 Add netbox-discovery-quickstart
  netbox-discovery-quickstart/.gitignore
  netbox-discovery-quickstart/0_install_host_tooling.sh
  netbox-discovery-quickstart/1_set_envvars.sh
  netbox-discovery-quickstart/2_start_netbox.sh
  netbox-discovery-quickstart/3_start_diode.sh
  netbox-discovery-quickstart/4_start_network.sh
  netbox-discovery-quickstart/5_start_network_discovery.sh
  netbox-discovery-quickstart/6_start_device_discovery.sh
  netbox-discovery-quickstart/LICENSE
  netbox-discovery-quickstart/README.md
  netbox-discovery-quickstart/images/device_ingestion_logs.png
  netbox-discovery-quickstart/images/diode_ingestion_logs.png
  netbox-discovery-quickstart/images/diode_reconciled_ip.png
  netbox-discovery-quickstart/images/diode_settings.png
  netbox-discovery-quickstart/images/ingested_devices.png
  netbox-discovery-quickstart/images/ingested_ethernet_1_1.png
  netbox-discovery-quickstart/images/ingested_interfaces.png
  netbox-discovery-quickstart/images/ingested_srl1.png
  netbox-discovery-quickstart/network/ios.clab.yml
  netbox-discovery-quickstart/network/srl.clab.yml
Labels: Internal, Markdown

#26 add code and readme for Event-Driven Network Automation with NetBox and Ansible Automation Platform webinar
  netbox-event-driven-ansible/README.md
  netbox-event-driven-ansible/playbooks/configure_login_banner.yml
  netbox-event-driven-ansible/playbooks/configure_ntp.yml
  netbox-event-driven-ansible/playbooks/configure_vlans.yml
  netbox-event-driven-ansible/playbooks/templates/ntp_config.j2
  netbox-event-driven-ansible/playbooks/templates/vlan_config.j2
  netbox-event-driven-ansible/rulebooks/netbox-webhook.yml
Labels: Markdown

#27 Add warning about known Diode VRF issue
  netbox-discovery-quickstart/README.md
Labels: Markdown
