Repository netboxlabs/netbox-learning, pull requests merged in 2025-01, with the labels that each got.

#28 Deleting branching_cli as the ideas there moved to: https://github.com/mrmrcoleman/pynetbox_branching/
  branching_cli/.gitignore
  branching_cli/create_site.py
  branching_cli/create_site_parameter.py
  branching_cli/netbox_branching_cli.py
  branching_cli/requirements.txt
Labels: Internal, Dependencies, Python

#30 added next section links
  automation-zero-to-hero/docs/5_Monitoring_Icinga.md
  automation-zero-to-hero/docs/7_Automated_Network_Changes_Ansible.md
Labels: documentation, Markdown

#31 Quickstart
  netbox-discovery-quickstart/README.md
Labels: Markdown

#32 Add note to cover smaller instances on DO
  netbox-discovery-quickstart/README.md
Labels: Markdown
